### ISSUE TITLE
Rebranding

### ISSUE THREAD

**Issue by renejfc** [Didas-git/lilybird#12]
###### _Hi, I'm not really sure if this is the right place for this, but since the discussion section isn't available, I'll just drop it here._

Basically, I'd like to propose a rebranding from Lilybird to **Buncord**. 

#### Why?
- It's easier and more intuitive to remember.
- It feels more like a unified concept between Bun and Discord.
- It feels like it could gain more engagement and traction "organically".
- And that's basically it, as a user I feel like it's just an intuitive fit that makes it attractive.

##### _NOTE: I want to clarify that I don't have anything against the current name and I don't want to diminish it either, I understand it could be something personal or sentimental and it's respectable if a rebranding is off the table._

**Comment by Didas-git** [comment]
The name wont be changed, we are not affiliated with bun and the library also works in node, not to speak that making name changes at this point would just bring more issues than help with anything at all
