### ISSUE TITLE
project was abandoned by teen dev

### ISSUE THREAD

**Issue by Ungolim** [Didas-git/lilybird#29]
typical

**Comment by Didas-git** [comment]
The project is not abandoned, im currently on vacation and do not find myself near a computer.
Development, together with a 0.8 version will come out once im back from vacation.

**Comment by Ungolim** [comment]
> The project is not abandoned, im currently on vacation and do not find myself near a computer. Development, together with a 0.8 version will come out once im back from vacation.

nigga you been on vacation since may 

![image](https://github.com/user-attachments/assets/b4faf277-22c4-4941-89b3-5295be75cc1b)

**Comment by Didas-git** [comment]
That was the winter one, you can check the progress o the [impx](https://github.com/Didas-git/lilybird/tree/impx) branch for whats been done to lilybird ever since

**Comment by xhyrom** [comment]
> > The project is not abandoned, im currently on vacation and do not find myself near a computer. Development, together with a 0.8 version will come out once im back from vacation.
> 
> nigga you been on vacation since may
> 
> ![image](https://private-user-images.githubusercontent.com/45174270/359837075-b4faf277-22c4-4941-89b3-5295be75cc1b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQyMzM2OTMsIm5iZiI6MTcyNDIzMzM5MywicGF0aCI6Ii80NTE3NDI3MC8zNTk4MzcwNzUtYjRmYWYyNzctMjJjNC00OTQxLTg5YjMtNTI5NWJlNzVjYzFiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIxVDA5NDMxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgyOWFiYTA2NWJjNDZmM2MzN2U0YWUxOGY4NDRjYTVjOTQ5Y2U2ODIxNjA5MTI0YzBjMDM3ZjZkODM1ZmNlMjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.hDVK3A655-QN9vs7ge805NP_Opxw86hsmVjWy3Lb1qM)

Let's keep the discussion respectful. Everyone, no matter their age, can be a good programmer and work on any project. If you're worried about the current lilybird status, why not offer a hand instead of being rude? We're all volunteers, and sometimes we can't contribute due to our lives. We want to have a friendly community where everyone feels welcome.
