### ISSUE TITLE
Add support for `USER` and `MESSAGE` interactions in `@lilybird/handler`

### ISSUE THREAD

**Issue by YoruNoKen** [Didas-git/lilybird#9]
![image](https://github.com/Didas-git/lilybird/assets/69751661/a04321c9-93d1-4916-9897-7a99dc6ab515)

**Comment by YoruNoKen** [comment]
error message
![image](https://github.com/Didas-git/lilybird/assets/69751661/a7b55dd9-2b9d-4222-ac2a-e47b75a13344)

**Comment by Didas-git** [comment]
The handlers currently only support `CHAT_INPUT` interactions, i could think about adding support for the other types (`USER` and `MESSAGE`).
As for the error message, thats more on you than really the handlers.
![image](https://github.com/Didas-git/lilybird/assets/80978939/379293d1-6a7a-40e2-b245-3f5e82b9a62a)

**Comment by YoruNoKen** [comment]
ah yea, I just changed its `type` to `ApplicationCommandType.USER` so it gave that error lul
